[project]
name = "teste"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv",
    "2captcha-python>=2.0.5",
    "fastapi",
    "playwright",
    "pydantic",
    "rich",
    "uvicorn",
    "python-multipart",
    "reportlab>=4.4.10",
    "pypdf>=6.9.2"
]
